# Generated by Django 5.1.3 on 2024-12-01 02:52

from django.db import migrations, models

import phone_numbers.managers


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hammersystemuser',
            managers=[
                ('objects', phone_numbers.managers.HammerSystemManager()),
            ],
        ),
        migrations.AddField(
            model_name='hammersystemuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Суперпользователь'),
        ),
    ]
