# Generated by Django 5.1.3 on 2024-12-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0003_alter_hammersystemuser_referal_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hammersystemuser',
            name='referal_users',
        ),
        migrations.AddField(
            model_name='hammersystemuser',
            name='invite_code',
            field=models.CharField(default='', max_length=6, verbose_name='Инвайт код'),
            preserve_default=False,
        ),
    ]
