# Generated by Django 5.1.3 on 2024-12-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0004_remove_hammersystemuser_referal_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hammersystemuser',
            name='auth_code',
            field=models.CharField(default='', max_length=4, verbose_name='Код авторизации'),
            preserve_default=False,
        ),
    ]
