# Generated by Django 5.1.3 on 2024-12-01 18:06

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0007_remove_hammersystemuser_referal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hammersystemuser',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Никнейм'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hammersystemuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
