# Generated by Django 5.1.3 on 2024-12-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0008_hammersystemuser_name_alter_hammersystemuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hammersystemuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='hammersystemuser',
            name='invite_code',
            field=models.CharField(max_length=6, unique=True, verbose_name='Инвайт код'),
        ),
    ]
