# Generated by Django 5.1.3 on 2024-12-01 18:13

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0009_remove_hammersystemuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hammersystemuser',
            name='invite_code',
            field=models.CharField(max_length=6, verbose_name='Инвайт код'),
        ),
        migrations.AlterField(
            model_name='hammersystemuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
