# Generated by Django 5.1.3 on 2024-12-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0010_alter_hammersystemuser_invite_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hammersystemuser',
            name='invite_code_changed',
            field=models.BooleanField(default=False),
        ),
    ]
